import { IsString, IsNumber, IsOptional, IsDateString } from 'class-validator';

export class CreateImageDto {
  @IsString()
  @IsOptional()  // Made optional since it will be generated by the backend
  image_id?: string;

  @IsString()
  trip_id: string;

  @IsString()
  image_url: string;

  @IsNumber()
  @IsOptional()
  latitude?: number | null;

  @IsNumber()
  @IsOptional()
  longitude?: number | null;

  @IsDateString()
  @IsOptional()
  taken_at?: string | null;

  @IsString()
  @IsOptional()
  country?: string | null;

  @IsString()
  @IsOptional()
  city?: string | null;

  @IsString()
  @IsOptional()
  state?: string | null;

  @IsString()
  @IsOptional()
  postal_code?: string | null;

  @IsString()
  @IsOptional()
  street?: string | null;
}